### PR TITLE
Update to Gradle 6.5.1

### LINKED ISSUE #28: Update to Gradle 5.
Currently the client library can only be built using Gradle 4 (latest tested version is 4.10.3). We should move this to use Gradle 5 and publish the library into central repositories.

### PR DESCRIPTION
**Pull request by lugehorsam**
- Upgrades to Gradle 6.5 from Gradle 4.0 and adds better support for Eclipse-based IDEs like VSCode (by default, disables warnings in generated code. And VSCode's Java plugin is Eclipse based.).
- Migrates all dependent `.proto` files into this repository.
- Adds `banGroupUsers` support to the SDK.
- Fixes tournament tests. Tournament objects must now have `end_time` specified if they do not have a reset schedule. I made a note to document this.
- There are still two outstanding tests that do not pass due to a server bug. I believe the issue is that tournament records without reset schedules expire prematurely. @mofirouz can provide more detail on the issue with the entire code path, I traced it through with him a bit I think there's one piece I am still missing. Also made a note to file an issue to Nakama for that.

Closes #28 and #32 and #33

### CODE REVIEW

**Comment by lugehorsam** [comment]
https://github.com/heroiclabs/nakama-java/pull/35/commits/b4694e6dda2eb251546907a7bc3dc0439e57b2ba addresses the flattening structure. working on the gateway files exclusions next.

**Comment by lugehorsam** [comment]
It took a few tries but b02edd59a7c4858746dce2ec1db65594bfe3089d excludes the gateway files. Verified by grepping the symbol table.

**Comment by lugehorsam** [comment]
@mofirouz @novabyte all PR feedback addressed, the only item remaining is a potential parsing issue that Mo talked with me about today, but has to get more information from a client about.

**Comment by lugehorsam** [comment]
shadowjar relocation - 2cfe83a

I thought the most time efficient way to test this was by looking at the classpath entries in the `.jar` - all third party deps now have the `nakama` prefix, e.g., ` nakama/com/google/protobuf/AbstractMessage.class`.

**Comment by lugehorsam** [comment]
@novabyte @mofirouz I talked through some additional items with Mo. I don't mind adding them to this PR, or you can take a look at the newest commits from yesterday and I can start a new PR.

**Comment by novabyte** [comment]
@lugehorsam Looks great. Nice work! 👍

**Pull request merged**
